cache: cargo
language: rust
sudo: required
rust: stable

install:
  - command -v mdbook || cargo install mdbook
  - command -v ghp || cargo install ghp

script:
  - mdbook build

after_success:
  # - if [ $TRAVIS_PULL_REQUEST = false ]; then
  - ghp -m "$(git rev-parse HEAD)" book &&
    git config user.name 'Jorge Aparicio' &&
    git config user.email 'japaricious@gmail.com' &&
    git push -fq https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages;

env:
  global:
    - secure: j33xtVJ5S009SlmbQaPlag2Yy2dZo1GTCgS9XoT7Gw0PXMXyaaQb5sPbOrPBVP5Um4YQKWRI04os6jmc/7jufzPvEhqHeFpeVzmOyVJ9V5zAfsMyROYrIGDpZgldpVIIamMcRWUqHt+hruUXs6Vr1Jce2TVL6CZEsxXDUo3fu2r2ijt2/EMlMo4TNf1zGls7F3ecCI6fNQxGvRaJSPyJbxDxsAO0097wS8iOwFywVReZiFjXy0AjCmd6w7OnANQqkgkMfICUPR80yBIrpalysUH0LiMaQlUer6MBdNpWgj73laP8/ua20s+NFujDlJV3Yuzaxly0X/506bCDn0T3wp66S5uYZ3z6u3AWwvoSh1t01EGME2GuoMKUW3YlB5doPfi3hyEfqj4HV8KOfcvtjl1V97cTVAkxW3VC348M8PloVUIrGRSI5mAQBGhB7VmvdHlfRP779uVugyRsZ9oP7v9+JfK9Uf8AdSHhyBJXLEbs2op/g4GaQzbiuJ38NtoXQSvjYPP+aqP57wItqZse6uAN1gdwCi+/ZMaThpravvon4nxnN8P2eNxH0J0jMBHYJ8tJp2shqcwcDdS2sZpSMoKSTrGD8qq+xvcnkyhYiQOPp+hL+S3vSRxq2P57PPBqCgrspHQKCCN8zOt4iLgVObMyrKrnugUJ3lysrz8YUaU=

branches:
  only:
    - master

notifications:
  email:
    on_success: never
  webhooks: https://homu.herokuapp.com/travis
