[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "led-roulette"
version = "0.1.0"

[dependencies]
aux = { path = "aux" }

[profile.dev]
codegen-units = 1

[profile.release]
debug = true
lto = true
