[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "pg"
version = "0.1.0"

[dependencies.f3]
default-features = false
features = [
    "default-exception-handler",
    "default-panic-fmt",
]
version = "0.3.0"
