[package]
name = "hello-world"
version = "0.1.0"
authors = ["Jorge Aparicio <japaricious@gmail.com>"]

[dependencies]
pg = { path = "pg" }

[profile.release]
lto = true

[profile.dev]
codegen-units = 1