[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "leds-again"
version = "0.1.0"

[dependencies]
pg = { path = "pg" }

[profile.release]
lto = true

[profile.dev]
codegen-units = 1